### ISSUE TITLE
S3 s3_bucket_count aws default quota (only?) available in us-east-1

### ISSUE THREAD

**Issue by ilons** [gravitational/aws-quota-checker#45]
First of all, thank you for this fantastic library, all the work going into it is much appreciated!

I don't know when this changed (or if this was always the case), but as of 30th of September 16:00 UTC (roughly), it seems like I'm no longer able to get the AWS default service quota for s3 L-DC2B2D3D.

Edit:
_My suspicion is that this is triggered by the AWS service team starting to add support for showing increased limits for this quota._

Steps to reproduce:
```python
import boto3
import botocore.config


client_kw = dict(config=botocore.config.Config(retries={'max_attempts': 15, 'mode': 'standard'}))
quota_kw = dict(ServiceCode='s3', QuotaCode='L-DC2B2D3D')
quota_regions = ['us-east-1', 'ap-south-1', 'ca-central-1', 'eu-central-1', 'sa-east-1']

for region in quota_regions:
    try:
        quota = session.client('service-quotas', region_name=region, **client_kw).get_aws_default_service_quota(**quota_kw)['Quota']
        print(f'Default quota in {region}:', quota)
    except botocore.exceptions.ClientError:
        print(f'Default service quotas not supported in {region}')
        continue
```
Gives:
```text
Default quota in us-east-1: {'ServiceCode': 's3', 'ServiceName': 'Amazon Simple Storage Service (Amazon S3)', 'QuotaArn': 'arn:aws:servicequotas:::s3/L-DC2B2D3D', 'QuotaCode': 'L-DC2B2D3D', 'QuotaName': 'General purpose buckets', 'Value': 100.0, 'Unit': 'None', 'Adjustable': True, 'GlobalQuota': True, 'UsageMetric': {'MetricNamespace': 'AWS/Usage', 'MetricName': 'ResourceCount', 'MetricDimensions': {'Class': 'None', 'Resource': 'GeneralPurposeBuckets', 'Service': 'S3', 'Type': 'Resource'}, 'MetricStatisticRecommendation': 'Maximum'}, 'Period': {'PeriodValue': 5, 'PeriodUnit': 'MINUTE'}}
Default service quotas not supported in ap-south-1
Default service quotas not supported in ca-central-1
Default service quotas not supported in eu-central-1
Default service quotas not supported in sa-east-1
```

As the [boto3 client](https://github.com/gravitational/aws-quota-checker/blob/teleport/aws_quota/check/quota_check.py#L48) for [getting the default quota](https://github.com/gravitational/aws-quota-checker/blob/teleport/aws_quota/check/quota_check.py#L24) simply uses whatever region is set for the session (which is shared for other calls), this fails unless you are checking quotas in us-east-1 explicitly.

**Comment by ilons** [comment]
As a workaround, I'm using this override for this check:
```python
import aws_quota.check.s3
from aws_quota.check.quota_check import get_default_service_quota


class BucketCountCheck(aws_quota.check.s3.BucketCountCheck):

    @property
    def maximum(self) -> int:
        try:
            return super().maximum
        except self.sq_client.exceptions.NoSuchResourceException:
            sq_client = self.boto_session.client(
                'service-quotas',
                region_name='us-east-1',
                config=getattr(self.sq_client, "_client_config"),
            )
            return int(get_default_service_quota(sq_client, self.service_code, self.quota_code)['Value'])
```

While not elegant, it works for now.

**Comment by taraspos** [comment]
Hi @ilons, thanks for reporting this. Yeah, AWS Service Quota is a bit mess. There is a whole medium article about that, haha:
- https://medium.com/@jsonk/the-limit-does-not-exist-hidden-visibility-of-aws-service-limits-4b786f846bc0


I added `quota_region_override` property and configured it to be `quota_region_override=us-east-1` for S3 bucket check.
- https://github.com/gravitational/aws-quota-checker/pull/48
